### ISSUE TITLE
Doctrine instance in resolvers

### ISSUE THREAD

**Issue by EnoahNetzach** [Youshido/GraphQLBundle#1]
Hi, I really appreciate this projects, but I am currently finding an obstacle: how am I supposed to make queries to doctrine in a resolver?

Should the bundle pass doctrine/composer (the latter preferably) down to the `Schema` instance from the controller?

Thanks! ^_^

**Comment by portey** [comment]
Hi, 
You must use ContainerAwareTypes, look here https://github.com/Youshido/GraphQLBundle/tree/master/Type

**Comment by EnoahNetzach** [comment]
love you <3

**Comment by viniychuk** [comment]
As a quick response – you can extend from `AbstractContainerAwareObjectType`, but we'll make an example of that by the end of this week.

**Comment by EnoahNetzach** [comment]
@viniychuk that will be really useful ;)

**Comment by EnoahNetzach** [comment]
thank you both so much
