### ISSUE TITLE
GraphQLController - undefined method named "json"

### ISSUE THREAD

**Issue by jorge-marques** [Youshido/GraphQLBundle#10]
Hi, it looks like there's a bug with GraphQLController

```
if (!$schemaClass || !class_exists($schemaClass)) {
    return $this->json([
        ['message' => 'Schema class ' . $schemaClass . ' does not exist']
    ]);
}
```

It should creating a JsonResponse instead, i think?

**Comment by tobias-nawa** [comment]
Packagist is not up to date. I added the repo directly to composer as described here: [https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) and required "dev-master".

**Comment by portey** [comment]
Hi,

yes, it was fixed, but there wasn't version with it in composer, so I just added and now you can update bundle.
