### ISSUE TITLE
GraphiQL Extension

### ISSUE THREAD

**Issue by andheiberg** [Youshido/GraphQLBundle#11]
It would seem that the assets for GraphiQL are not accessible.

I tried to install GraphiQL `npm install --save graphiql`.

But that doesn't mean that the assets are actually assessable.

Gonna look and see if I can get it working. If I do I will update the issue and close it.

But if you answer this in the meantime that would be greatly appreciated.

**Comment by portey** [comment]
Hi, 

Did you try command `php bin/console assets:install` ?

**Comment by andheiberg** [comment]
I did not :( sorry new to the Symfony ecosystem. That's great though! Perhaps we should update the README?
