### ISSUE TITLE
AbstractContainerAwareField is not working

### ISSUE THREAD

**Issue by iainmckay** [Youshido/GraphQLBundle#13]
It seems since last nights commit that `AbstractContainerAwareField` isn't being given the container. I've traced through and it seems that `Youshido\GraphQLBundle\Execution\Processor::resolveFieldValue` is no longer being called and that's where the container is set.

Is this by design, should we perhaps be using `ResolveInfo::getExecutionContext()->getContainer()`?

Thanks

**Comment by portey** [comment]
Hi
we just fixed it, please use version 1.2.1

**Comment by iainmckay** [comment]
Great, I can confirm it works.

Thanks
