### ISSUE TITLE
Best way to compose/override schema ?

### ISSUE THREAD

**Issue by erichard** [Youshido/GraphQLBundle#14]
Hello,

I'm currently working on a generic cart API that will be used in several projects. I thought about graphQL to do it. 

What will be the best way to provide a generic schema in a shared bundle but allow customization in project. Currently it seems that types and fields cannot be easily overriden...

Also how can we compose schema. Think about this use case, my generic cart bundle provide a schema with a cart query and some mutations, and the project itself have also its own schema with business schema. Is it better to have two endpoints or to merge both schema ?

**Comment by viniychuk** [comment]
@erichard Hi, I'll have an example shared soon, by the next release of GraphQL library which is in less then a week.
