### ISSUE TITLE
Why schema class and not service?

### ISSUE THREAD

**Issue by akomm** [Youshido/GraphQLBundle#16]
Being forced to use `Symfony\Component\DependencyInjection\ContainerAwareInterface` does not feel good. Any reason why no service is used? It is possible to set a default blank Schema at least and give the ability to override the service or just add a definition via compiler pass based on provided config.

**Comment by viniychuk** [comment]
We're actually moving towards using Schema through the ExecutionContext which is already a service. Also, you can define your schema as a service by implementing "graphql.schema" service. I'll share an example

**Comment by akomm** [comment]
Going to check this out thanks
