### ISSUE TITLE
The definition for "youshido.graphql.schema" has no class

### ISSUE THREAD

**Issue by rwpino** [Youshido/GraphQLBundle#2]
When following the bundle installation process as per the read me I receive the following error

> [Symfony\Component\DependencyInjection\Exception\RuntimeException]
>   The definition for "youshido.graphql.schema" has no class. If you intend to inject this service dynamically at runtime
>   , please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abs
>   tract=true, otherwise specify a class to get rid of this error.

When I start to run the app in the local web server to see the {"errors":[{"message":"You have to set GraphQL Schema to process"}]}, I get the above exception.

**Comment by viniychuk** [comment]
Thanks you for reporting it @rwpino , it will be fixed asap..

**Comment by rwpino** [comment]
I did a work around and added the following in the file "youshido/graphql-bundle/Resources/config/services.yml" and I was able to ignore that error

> youshido.graphql.schema:
>           synthetic: true

But after that I get an error in "youshido/graphql-bundle/Controller/GraphQLController.php" on line 49 that its not able to find the setSchema method inside "youshido/graphql-bundle/Execution/Processor.php".

**Comment by portey** [comment]
@rwpino, you can update your project to use latest versions of bundle, it's fixed there.
