### ISSUE TITLE
Does it work with legacy Symfony

### ISSUE THREAD

**Issue by jbonigomes** [Youshido/GraphQLBundle#20]
Great project, I was just wondering if this package works with older versions of Symfony, 1.4 in particular

**Comment by viniychuk** [comment]
Hi @jbonigomes ,
Take a look at the controller we're using, it's very simple. Let me  know if there anything unclear, we can create a legacy branch that you can use. 
https://github.com/Youshido/GraphQLBundle/blob/master/Controller/GraphQLController.php

**Comment by jbonigomes** [comment]
Thanks @viniychuk, I have been living in the node.js world for a while now, my PHP skills are rather rusty, is there a way to install the package without composer? Is it too much trouble for you guys getting a legacy branch? Thanks very much

**Comment by viniychuk** [comment]
@jbonigomes will try to do that on the weekend, shouldn't take long

**Comment by viniychuk** [comment]
@jbonigomes also, take a look at the original library, you might want to just use that for the legacy project – http://gitHub.com/youshido/graphql

**Comment by jbonigomes** [comment]
Thanks Youshido, I will try the legacy project over the weekend, really appreciate your help

**Comment by jbonigomes** [comment]
In fact, this does not work with my required version of PHP, 5.4, believe it or not
