### ISSUE TITLE
Schema command generator output.

### ISSUE THREAD

**Issue by Biromain** [Youshido/GraphQLBundle#33]
I just discovered your bundle, sorry if i misunderstand something.
Schema generator comand output seem not good
https://github.com/Youshido/GraphQLBundle/blob/master/Command/GraphQLConfigureCommand.php#L151

`default` to `defaultValue`

Regards,

**Comment by viniychuk** [comment]
@Biromain thank you, good catch! Will update it tonight!

**Comment by biromain** [comment]
@viniychuk no problem, thank you for your reactivity. It's a good indice to continu to learn and use your bundle. 👍
